{
  "comments": [
    {
      "key": {
        "uuid": "fa81d914_0a63e2dc",
        "filename": "backend/cephapi/api.go",
        "patchSetId": 3
      },
      "lineNbr": 117,
      "author": {
        "id": 1006044
      },
      "writtenOn": "2016-01-26T06:46:34Z",
      "side": 1,
      "message": "Is there a chance that this task is indefinitely running? How we can handle that? Does calamari handles this case properly? What I mean was does calamari task times out after a specific period?",
      "range": {
        "startLine": 117,
        "startChar": 2,
        "endLine": 117,
        "endChar": 29
      },
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_76836704",
        "filename": "backend/cephapi/api.go",
        "patchSetId": 3
      },
      "lineNbr": 117,
      "author": {
        "id": 1006049
      },
      "writtenOn": "2016-01-27T06:46:17Z",
      "side": 1,
      "message": "Below we are checking for reqStatus.Err.\n\nI feel that should be fine.",
      "parentUuid": "fa81d914_0a63e2dc",
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_ea63eeda",
        "filename": "backend/cephapi/api.go",
        "patchSetId": 3
      },
      "lineNbr": 138,
      "author": {
        "id": 1006044
      },
      "writtenOn": "2016-01-26T06:46:34Z",
      "side": 1,
      "message": "check for error only if complete. if error, return error, otherwise success",
      "range": {
        "startLine": 133,
        "startChar": 2,
        "endLine": 138,
        "endChar": 3
      },
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_96861b12",
        "filename": "backend/cephapi/api.go",
        "patchSetId": 3
      },
      "lineNbr": 138,
      "author": {
        "id": 1006049
      },
      "writtenOn": "2016-01-27T06:46:17Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "fa81d914_ea63eeda",
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_8aa6f20e",
        "filename": "backend/cephapi/handler/handler.go",
        "patchSetId": 3
      },
      "lineNbr": 31,
      "author": {
        "id": 1006044
      },
      "writtenOn": "2016-01-26T06:46:34Z",
      "side": 1,
      "message": "func name not appropriate I guess :)",
      "range": {
        "startLine": 31,
        "startChar": 5,
        "endLine": 31,
        "endChar": 14
      },
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_b67cff21",
        "filename": "backend/cephapi/handler/handler.go",
        "patchSetId": 3
      },
      "lineNbr": 31,
      "author": {
        "id": 1006049
      },
      "writtenOn": "2016-01-27T06:46:17Z",
      "side": 1,
      "message": "Will change it to invokeUpdateRestApi",
      "parentUuid": "fa81d914_8aa6f20e",
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_eaaa0ed1",
        "filename": "provider/cluster.go",
        "patchSetId": 3
      },
      "lineNbr": 486,
      "author": {
        "id": 1006044
      },
      "writtenOn": "2016-01-26T06:46:34Z",
      "side": 1,
      "message": "Why return here? Log error and continue. I don\u0027t think we need to fail the expand cluster here. Log and update the task status properly",
      "range": {
        "startLine": 486,
        "startChar": 3,
        "endLine": 486,
        "endChar": 9
      },
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_d677b339",
        "filename": "provider/cluster.go",
        "patchSetId": 3
      },
      "lineNbr": 486,
      "author": {
        "id": 1006049
      },
      "writtenOn": "2016-01-27T06:46:17Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "fa81d914_eaaa0ed1",
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_0aba0223",
        "filename": "provider/cluster.go",
        "patchSetId": 3
      },
      "lineNbr": 584,
      "author": {
        "id": 1006044
      },
      "writtenOn": "2016-01-26T06:46:34Z",
      "side": 1,
      "message": "As I commented earlier, no need to fail the expand cluster here. Log and update task with failed pools failed to update and proceed. do you agree?",
      "range": {
        "startLine": 583,
        "startChar": 3,
        "endLine": 584,
        "endChar": 15
      },
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fa81d914_f676773d",
        "filename": "provider/cluster.go",
        "patchSetId": 3
      },
      "lineNbr": 584,
      "author": {
        "id": 1006049
      },
      "writtenOn": "2016-01-27T06:46:17Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "fa81d914_0aba0223",
      "revId": "66741ae9d072c4c042015b52a39564d7799f3a18",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}